// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TestAuth2Mvc.Migrations
{
    [DbContext(typeof(TestMvcContext))]
    partial class TestMvcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("TestAuth2Mvc.Models.MvcObject", b =>
                {
                    b.Property<int>("MvcObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MvcObjectName")
                        .HasColumnType("TEXT");

                    b.HasKey("MvcObjectId");

                    b.ToTable("Object");
                });
#pragma warning restore 612, 618
        }
    }
}
